######################################################################
# Automatically generated by qmake (1.05a) Wed May 21 15:38:59 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += MyOpenGLWidget.h
SOURCES += main.cpp MyOpenGLWidget.cpp
CONFIG          += qt opengl warn_on release m
