######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 11 15:01:28 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += /usr/qt/3/include
LIBRARYPATH += /usr/qt/3/lib

# Input
HEADERS += GLError.h MyOpenGLWidget.h land.h
SOURCES += main.cpp MyOpenGLWidget.cpp 
CONFIG  += qt opengl warn_on release m

TARGET          = land
OBJECTS_DIR     = obj
MOC_DIR         = moc
