######################################################################
# Automatically generated by qmake (1.05a) Thu Jun 26 15:05:40 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += FormulaShape.h MyOpenGLWidget.h
SOURCES += MyOpenGLWidget.cpp main.cpp
CONFIG          += qt opengl warn_on release m
TARGET          = formulaSaver
OBJECTS_DIR     = obj
MOC_DIR         = moc
