
/****************************************************************************** 
* This file defines the tree menu with it's items and submenus.               *
* This file is generated by:						      *
* http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/VeriCool.pl          *
******************************************************************************/ 
 
// User-defined tree menu data. 
 
var treeMenu           = new TreeMenu();
var treeMenuName       = "myMenu_4.0";
var treeMenuDays       = 0;
var treeMenuFrame      = "Mainframe";
var treeMenuImgDir     = "pics/";
var treeMenuBackground = "http://avweb.etxb.ericsson.se/~pr-traco/VeriCool/pics/VertLinesBig.gif";
var treeMenuBgColor    = "#000000";
var treeMenuFgColor    = "#000000";
var treeMenuHiBg       = "#008080";
var treeMenuHiFg       = "#FFFFFF";
var treeMenuFont       = "MS Sans Serif,Arial,Helvetica";
var treeMenuFontSize   = 1;
var treeMenuRoot       = "VeriCool View Tree";
var treeMenuFolders    = 1;
var treeMenuAltText    = "true";
 
// Define the items for the tree menu. 

treeMenu.addItem(new TreeMenuItem("TRACO_R1A03", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewBlockInfo.pl?TRACO_R1A03.2000_07_04.10_15/", "Main"));
treeMenu.addItem(new TreeMenuItem("TRACO_R1A02", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewBlockInfo.pl?TRACO_R1A02.2000_07_04.10_15/", "Main"));
treeMenu.addItem(new TreeMenuItem("TRACO_R1A01", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewBlockInfo.pl?TRACO_R1A01.2000_07_04.10_14/", "Main"));
 
var TRACO_R1A03 = new TreeMenu();
TRACO_R1A03.addItem(new TreeMenuItem("TB"));
TRACO_R1A03.addItem(new TreeMenuItem("ST"));
TRACO_R1A03.addItem(new TreeMenuItem("Release Info", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A03.2000_07_04.10_15/web/release.info", "Main", "menu_link_ref.gif"));
treeMenu.items[0].makeSubmenu(TRACO_R1A03);
 
var TRACO_R1A02 = new TreeMenu();
TRACO_R1A02.addItem(new TreeMenuItem("TB"));
TRACO_R1A02.addItem(new TreeMenuItem("ST"));
TRACO_R1A02.addItem(new TreeMenuItem("Release Info", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A02.2000_07_04.10_15/web/release.info", "Main", "menu_link_ref.gif"));
treeMenu.items[1].makeSubmenu(TRACO_R1A02);
 
var TRACO_R1A01 = new TreeMenu();
TRACO_R1A01.addItem(new TreeMenuItem("TB"));
TRACO_R1A01.addItem(new TreeMenuItem("ST"));
TRACO_R1A01.addItem(new TreeMenuItem("Release Info", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A01.2000_07_04.10_14/web/release.info", "Main", "menu_link_ref.gif"));
treeMenu.items[2].makeSubmenu(TRACO_R1A01);
 
var TRACO_R1A03$TB = new TreeMenu();
TRACO_R1A03$TB.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-TB_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A03$TB.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-TB_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A03$TB.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-TB_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A03.items[0].makeSubmenu(TRACO_R1A03$TB);
 
var TRACO_R1A03$ST = new TreeMenu();
TRACO_R1A03$ST.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-ST_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A03$ST.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-ST_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A03$ST.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A03.2000_07_04.10_15/web/ROP1011603-ST_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A03.items[1].makeSubmenu(TRACO_R1A03$ST);
 
var TRACO_R1A02$TB = new TreeMenu();
TRACO_R1A02$TB.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-TB_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A02$TB.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-TB_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A02$TB.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-TB_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A02.items[0].makeSubmenu(TRACO_R1A02$TB);
 
var TRACO_R1A02$ST = new TreeMenu();
TRACO_R1A02$ST.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-ST_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A02$ST.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-ST_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A02$ST.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A02.2000_07_04.10_15/web/ROP1011603-ST_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A02.items[1].makeSubmenu(TRACO_R1A02$ST);
 
var TRACO_R1A01$TB = new TreeMenu();
TRACO_R1A01$TB.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-TB_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A01$TB.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-TB_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A01$TB.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-TB_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A01.items[0].makeSubmenu(TRACO_R1A01$TB);
 
var TRACO_R1A01$ST = new TreeMenu();
TRACO_R1A01$ST.addItem(new TreeMenuItem("Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-ST_R2A03.files", "Main", "menu_link_local.gif"));
TRACO_R1A01$ST.addItem(new TreeMenuItem("Changed Files", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewCHFiles.pl?TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-ST_R2A03", "Main", "menu_link_local.gif"));
TRACO_R1A01$ST.addItem(new TreeMenuItem("Comments", "http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/PrintFile.pl?/home/pr-traco/releases/releaseDir/TRACO_R1A01.2000_07_04.10_14/web/ROP1011603-ST_R2A03.comments", "Main", "menu_link_local.gif"));
TRACO_R1A01.items[1].makeSubmenu(TRACO_R1A01$ST);
 
