######################################################################
# Automatically generated by qmake (1.05a) Sat Oct 18 16:39:37 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .
CONFIG          += qt opengl warn_on release m

# Input
HEADERS += MyOpenGLWidget.h
SOURCES += main.cpp MyOpenGLWidget.cpp
