######################################################################
# Automatically generated by qmake (1.05a) Thu Apr 17 09:55:34 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += GLError.h MyOpenGLWidget.h
SOURCES += main.cpp MyOpenGLWidget.cpp

CONFIG  += qt opengl warn_on release m
TARGET          = test
OBJECTS_DIR     = obj
MOC_DIR         = moc
