######################################################################
# Automatically generated by qmake (1.05a) Mon Apr 14 11:39:40 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += GLError.h MyOpenGLWidget.h colorsetter.h
SOURCES += main.cpp MyOpenGLWidget.cpp
OBJECTS_DIR     = obj
MOC_DIR         = moc
CONFIG          += qt opengl warn_on release m
