#!/usr/local/bin/perl
#########################################################################
# Script name: Release Tree 1.0						#
# Written by: Tomas Mannerstedt qtxtman@etxb.ericsson.se		#
# First version released: 00-06-26					#
# Comments: This script sets up the $mymenufile for the treeMenuCode.js	#
# script. The treeMenuCode.js is downloaded from www.brainjar.com. Visit#
# website for FAQ's. The treeMenuCode.js -script may be used on an 	#
# intranet, but is not free to distribute without permission.		#
#########################################################################
# Define vareables							#

# The file where the vareables for the VeriCool and TR scripts are	#
# stored.								#
$varfile = "/home/htdocs/cgi-bin/Mustang/VeriCool/VeriCoolVareables.pl";

# Done									#
#########################################################################
# Get the vareables.							#

do $varfile;

# Done									#
#########################################################################
# Get the release dirs.							#

chdir($basedir);
$dirs = `/usr/bin/ls -Fp | grep '/'`;
@rel_dirs = split(/\n/, $dirs);

# Done									#
#########################################################################
# Sort the releases by date-time-name.					#

foreach $dir (@rel_dirs) {
	$dir =~ s/\///g;
	($release, $date, $time) = split(/\./, $dir);
	$revdirname = join('.', $date, $time, $release);
	push(@revdirnames, $revdirname);
}

@rel_dirs = ();
@sort_rel_dirs_rev = reverse(sort @revdirnames);

foreach $dir (@sort_rel_dirs_rev) {
	($date, $time, $release) = split(/\./, $dir);
	$time = join('', $time, "\/");
	$rel_dir_name = join('.', $release, $date, $time);
	push(@rel_dirs, $rel_dir_name);
}

# Done									#
#########################################################################
# Push releases to outputlist.						#

foreach $dir (@rel_dirs) {
	($release, @trash) = split(/\./, $dir);
	push(@output, "treeMenu.addItem(new TreeMenuItem(\"$release\", \"http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/ViewBlockInfo.pl?$dir\", \"Main\"))\;");
}

push(@output, " ");

# Done									#
#########################################################################
# Get the blocks and send them to outputlist.				#

$numintree = 0;

foreach $dir (@rel_dirs) {
	($release, @trash) = split(/\./, $dir);
	push(@output, "var $release = new TreeMenu()\;");

	open(RELEASEFILE, "<$basedir/$dir/web/release.conf");
	@conf_file = <RELEASEFILE>;
	close RELEASEFILE;

	foreach $row (@conf_file) {
		($block, $block_filebase, @trash) = split(/;/, $row);
		push(@output, "$release.addItem(new TreeMenuItem(\"$block\"))\;");
		push(@rel_block, "$release\$$block");
		push(@rel_block_files, "$dir\web/$block_filebase");
	}

	push(@output, "$release.addItem(new TreeMenuItem(\"Release Info\", \"$cgi_url/PrintFile.pl?$basedir/$dir\web/$rel_info_filename\", \"Main\", \"menu_link_ref.gif\"))\;");

	push(@output, "treeMenu.items[$numintree].makeSubmenu($release)\;");
	push(@output, " ");
	$numintree ++;
}

# Done									#
#########################################################################
# Get the comments and the files/chfilesdir and send them to outputlist.#

$numintree = (-1);
$dirno = 0;

foreach $rel_block (@rel_block) {
	push(@output, "var $rel_block = new TreeMenu()\;");
	($release, $block) = split(/\$/, $rel_block);

	if ($last_rel eq $release || $last_rel eq "") {
		$numintree ++;
		$last_rel = $release;
	}
	else {
		$numintree = 0;
		$last_rel = $release;
	}

	push(@output, "$rel_block.addItem(new TreeMenuItem(\"Files\", \"$cgi_url/PrintFile.pl?$basedir/@rel_block_files[$dirno].files\", \"$mainframe\", \"menu_link_local.gif\"))\;");
	push(@output, "$rel_block.addItem(new TreeMenuItem(\"Changed Files\", \"$cgi_url/ViewCHFiles.pl?@rel_block_files[$dirno]\", \"$mainframe\", \"menu_link_local.gif\"))\;");
	push(@output, "$rel_block.addItem(new TreeMenuItem(\"Comments\", \"$cgi_url/PrintFile.pl?$basedir/@rel_block_files[$dirno].comments\", \"$mainframe\", \"menu_link_local.gif\"))\;");
	push(@output, "$release.items[$numintree].makeSubmenu($rel_block)\;");
	push(@output, " ");

	$dirno ++;
}

# Done									#
#########################################################################
# Print the output.							#

open(JSFILE, ">$webdir/$mymenufile") || die "Err: cant find: $webdir/$mymenufile !!!\n";
print JSFILE <<_END_;

/****************************************************************************** 
* This file defines the tree menu with it's items and submenus.               *
* This file is generated by:						      *
* http://avweb.etxb.ericsson.se/cgi-bin/Mustang/VeriCool/VeriCool.pl          *
******************************************************************************/ 
 
// User-defined tree menu data. 
 
var treeMenu           = new TreeMenu();
var treeMenuName       = "$tree_menu_name";
var treeMenuDays       = $tree_menu_days;
var treeMenuFrame      = "$tree_menu_frame";
var treeMenuImgDir     = "$picdir/";
var treeMenuBackground = "$baseurl$picdir/$menubg";
var treeMenuBgColor    = "$tree_menu_bg_color";
var treeMenuFgColor    = "$tree_menu_fg_color";
var treeMenuHiBg       = "$tree_menu_hi_bg_color";
var treeMenuHiFg       = "$tree_menu_hi_fg_color";
var treeMenuFont       = "$tree_menu_font";
var treeMenuFontSize   = $tree_menu_font_size;
var treeMenuRoot       = "$menu_root_name";
var treeMenuFolders    = $tree_menu_folders;
var treeMenuAltText    = "$tree_menu_alt_txt";

var treeMenuMainUrl    = "$baseurl\Main.shtml";
var treeMenuMainFrame  = "$mainframe";

 
// Define the items for the tree menu. 

_END_

foreach $row (@output) {
	print JSFILE "$row\n";
}

close JSFILE;

# Done									#
#########################################################################
# Redirect to $website							#

print "Location: $website\n\n";

# Done									#
#########################################################################
